# Generated by Django 3.1.2 on 2020-12-12 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='projectname',
        ),
        migrations.AddField(
            model_name='project',
            name='group_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='project_members', through='homepage.Member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='requests',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
