# Generated by Django 3.1.2 on 2020-12-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201212_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requests',
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_requests',
            field=models.ManyToManyField(related_name='project_requests', through='homepage.Requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
